# Generated by Django 4.2.5 on 2023-11-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cafe', '0002_dish_photo_alter_category_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
    ]
