# Generated by Django 4.2.5 on 2023-11-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cafe', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
